#!/usr/bin/env python3
import tty, termios
import random
import sys

def clear():
  print(chr(27) + "[2J")

def getch():
    """getch() -> key character

    Read a single keypress from stdin and return the resulting character. 
    Nothing is echoed to the console. This call will block if a keypress 
    is not already available, but will not wait for Enter to be pressed. 

    If the pressed key was a modifier key, nothing will be detected; if
    it were a special function key, it may return the first character of
    of an escape sequence, leaving additional characters in the buffer.
    """
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch

cards = []
redo = []

file_path = sys.argv[1]
with open(file_path) as f:
  for line in f:
    cards.append(line.rstrip())

random.shuffle(cards)
clear()

while 1:
  # End flash card exercise when no cards left
  if 0 == len(cards):
    break;

  for card in cards:
    s = card.split('^')
    print(s[0].strip() + "\n")
    print(s[1].strip() + "\n")

    key = getch()
    if 'q' == key or 'Q' == key:
      exit(0)

    for n in range(2, len(s)):
      print("\t- " + s[n].strip())

    while 1:
      key = getch()
      if 'r' == key or 'R' == key:
        redo.append(line)
        break
      elif 'n' == key or 'N' == key:
        break
      elif 'q' == key or 'Q' == key:
        exit(0)

    clear()

  # Finised one loop, run again with cards marked as 'redo'
  cards = redo
  redo = []
